spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kkw?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #直接打印了返回结果
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  level:
    #日志中打印sql
    com.example.demo.web.dao: debug
server:
  port: 8081